### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by danmed** [audiofreak9/HA-Bridge_Control#1]
Hi,

this is exactly what i'm looking for however i've had to turn off the security settings on HA-Bridge.. 

any ideas how i can leave that enabled but still use your control page?

**Comment by audiofreak9** [comment]
You are correct.  I have been working on enhancements to the code the last few weeks.  I'll see what I can do to create control with authentication.

**Comment by audiofreak9** [comment]
@danmed I just committed a major code update to the HA Bridge Control.  You can now use it with the bridge when the username/password security is set.  Be sure to edit the config.php file with the same username and password as you have set for the bridge -OR- make a new user for this control page.

**Comment by danmed** [comment]
Awesome.. looks like it's working.. cheers
